apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
    version: v1.2
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: gbolo/sample-app:1.2
        ports:
        - containerPort: 60021
        env:
        - name: APP_SERVER_BIND_PORT
          value: "60021"
        - name: APP_DATABASE_DSN     # Improvement: use a secret to store the password
          value: "sample-app:$SECRET_PASSWORD@tcp(mysql:3306)/sampledb"
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-password
              key: password
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "100Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 60021
          initialDelaySeconds: 5 
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 60021
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP
      port: 60021
      targetPort: 60021

